//Course
export const GET_LIST_COURSE = "GET_LIST_COURSE";
export const GET_CATEGORY_COURSE = "GET_CATEGORY_COURSE";
export const CHOOSE_CATEGORY = "CHOOSE_CATEGORY";
export const COURSE_DETAIL = "COURSE_DETAIL";
export const ADD_CART = "ADD_CART";
export const DELETE_CART = "DELETE_CART";

//User
export const SIGN_UP = "SIGN_UP";
export const LOGIN = "LOGIN";
export const LOGOUT = 'LOGOUT';
export const GET_THONGTIN_USER = " GET_THONGTIN_USER";
export const REGISTER_COURSE = "REGISTER_COURSE";
export const UPDATE_THONGTIN = "UPDATE_THONGTIN";

//ADMIN

export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const GET_LIST_USER = "GET_LIST_USER";
export const GET_MALOAI = "GET_MALOAI";
export const FILTER_MALOAI = "FILTER_MALOAI";
export const GET_COURSE_CHOXETDUYET = "GET_COURSE_CHOXETDUYET";
export const FILTER_USER = "FILTER_USER";
export const GET_DANHSACH_CHOXETDUYET = "GET_DANHSACH_CHOXETDUYET";
export const GET_DANHSACHHOCVIEN_KHOAHOC = "GET_DANHSACHHOCVIEN_KHOAHOC";
export const HIENTHI_USER = "HIENTHI_USER";
export const UPDATE_USER = "UPDATE_USER";